import { NextResponse } from "next/server";

export async function POST(request: Request) {
  try {
    const { transcript, participants, meetingContext } = (await request.json()) as { 
      transcript: string[]; 
      participants?: string[];
      meetingContext?: { language?: string; region?: string; meetingType?: string; };
    };

    if (!transcript?.length) {
      return NextResponse.json({ error: "Transcript is empty or missing." }, { status: 400 });
    }

    const transcriptText = transcript.join("\n");
    const now = new Date();
    const dateStr = now.toLocaleDateString("en-US", { weekday: "long", year: "numeric", month: "long", day: "numeric" });
    const timeStr = now.toLocaleTimeString("en-US", { hour: "2-digit", minute: "2-digit", timeZoneName: "short" });

    const languageContext = meetingContext?.language === "nigerian-english" 
      ? `You are an expert at understanding Nigerian English, including local idioms, phrasing, and pronunciation patterns. Interpret Igbo, Yoruba, and Hausa words or phrases that appear in otherwise English conversations contextually.`
      : "";
    const meetingType = meetingContext?.meetingType?.toLowerCase() ?? "default";
    const meetingTypePrompt = (() => {
      switch (meetingType) {
        case "board":
          return "Produce formal board-level minutes. Focus on governance decisions, motions, voting outcomes, and high-level strategic summaries. Use structured headings and formal language.";
        case "standup":
          return "Create concise stand-up style minutes. For each speaker list: (1) what they completed, (2) what they plan to do next, (3) any blockers. Keep it brief and scannable.";
        case "retro":
          return "Generate retrospective minutes. Use three sections per team: What Went Well, What Didn't Go Well, and Action Items. Be specific and solution-oriented.";
        case "workshop":
          return "Write workshop minutes. Capture the agenda, key activities, group discussions, breakout findings, and all outputs or deliverables produced.";
        case "client":
          return "Produce client-meeting minutes in a polished, professional tone suitable for external sharing. Emphasise commitments, timelines, and next steps.";
        default:
          return "Produce comprehensive, professional meeting minutes suitable for any general business meeting.";
      }
    })();

    const systemPrompt = `You are a highly experienced corporate secretary with 20+ years writing formal board-level and executive meeting minutes for international companies.
${languageContext}
${meetingTypePrompt}

You are an expert at:
- Correcting obvious speech-to-text errors — repeated words, phonetic misspellings, filler words — without changing the speaker's meaning
- Attributing statements accurately to the correct named speaker
- Writing formal, professional meeting minutes that capture substance and intent, not just literal words

Your minutes must:
- Sound written by a human professional secretary, not an AI
- Use formal past tense ("The team discussed…", "It was agreed that…", "Mr Adeyemi proposed…")
- Capture the substance of discussions — the actual reasoning, positions, and debates
- Include all decisions with clear attribution
- Present action items in a structured table
- Be formatted in clean, professional Markdown`;

    const attendanceBlock = participants && participants.length > 0
      ? `REGISTERED PARTICIPANTS (from meeting database — this list is authoritative and complete, include ALL of them in the Attendance section even if they did not speak):\n${participants.map((p, i) => `${i + 1}. ${p}`).join("\n")}\n\n`
      : `REGISTERED PARTICIPANTS: None recorded in database. Derive attendance from transcript speakers only.\n\n`;

    const userPrompt = `Please produce complete, formal meeting minutes from the transcript below.

IMPORTANT INSTRUCTIONS:
- The transcript was generated by speech-to-text software and may contain errors — use your judgement to interpret meaning
- Speakers are identified by their name at the start of each line
- Do not omit any speaker or topic just because the transcription looks imperfect
- For the ATTENDANCE section, use the REGISTERED PARTICIPANTS list below if provided — it is accurate and authoritative

MEETING DATE: ${dateStr}
MEETING TIME: ${timeStr}

${attendanceBlock}RAW TRANSCRIPT (STT):
${transcriptText}

---

Write the minutes in this exact format:

# MEETING MINUTES

**Date:** ${dateStr}
**Time:** ${timeStr}
**Record Prepared By:** Quorum AI Secretary
**Status:** Official Record — Pending Approval

---

## 1. ATTENDANCE

*List EVERY person from the REGISTERED PARTICIPANTS list above. Also include any additional speakers found in the transcript who are not on that list. Mark the host where known.*

---

## 2. CALL TO ORDER

*Who opened the meeting, time, stated purpose, and any quorum confirmation.*

---

## 3. PROCEEDINGS

*For each major topic discussed, write a full paragraph as a professional secretary would.*

### 3.1 [First Topic]

### 3.2 [Second Topic]

---

## 4. DECISIONS RECORDED

*Numbered list of every formal or informal decision made.*

1. 
2.

---

## 5. ACTION ITEMS

| # | Action Required | Owner | Target Date | Priority |
|---|-----------------|-------|-------------|----------|
| 1 | | | | High / Medium / Low |

---

## 6. MATTERS FOR FOLLOW-UP

*Items deferred, tabled, or requiring future discussion.*

---

## 7. ADJOURNMENT

*How and at what time the meeting concluded.*

---

*Prepared by Quorum AI Secretary · ${dateStr}*`;

    const messages = [
      { role: "system", content: systemPrompt },
      { role: "user", content: userPrompt },
    ] as const;

    const createStreamHelper = (response: Response) => {
      const encoder = new TextEncoder();
      const decoder = new TextDecoder();
      return new ReadableStream({
        async start(controller) {
          if (!response.body) { controller.close(); return; }
          const reader = response.body.getReader();
          let buffer = "";
          try {
            while (true) {
              const { done, value } = await reader.read();
              if (done) break;
              buffer += decoder.decode(value, { stream: true });
              const lines = buffer.split('\n');
              buffer = lines.pop() ?? "";
              for (const line of lines) {
                const trimmed = line.trim();
                if (!trimmed) continue;
                if (trimmed === 'data: [DONE]') { controller.close(); return; }
                if (trimmed.startsWith('data: ')) {
                  try {
                    const data = JSON.parse(trimmed.slice(6));
                    const content = data.choices?.[0]?.delta?.content;
                    if (content) controller.enqueue(encoder.encode(content));
                  } catch (e) { /* partial or error JSON */ }
                }
              }
            }
            controller.close();
          } catch (e) {
            controller.error(e);
          }
        }
      });
    };

    const callGroq = async () => {
      const apiKey = process.env.GROQ_API_KEY;
      if (!apiKey) throw new Error("GROQ_API_KEY is not configured.");
      const response = await fetch("https://api.groq.com/openai/v1/chat/completions", {
        method: "POST",
        headers: { "Content-Type": "application/json", Authorization: `Bearer ${apiKey}` },
        body: JSON.stringify({
          model: process.env.GROQ_MODEL || "llama-3.3-70b-versatile",
          messages,
          temperature: 0.2,
          max_tokens: 4000,
          stream: true,
        }),
      });
      if (!response.ok) { 
        const text = await response.text().catch(() => "");
        const err = new Error(text || `Groq API responded with status ${response.status}`); 
        (err as any).status = response.status; 
        throw err; 
      }
      return new Response(createStreamHelper(response), { headers: { "Content-Type": "text/plain; charset=utf-8" } });
    };

    const callOpenAI = async () => {
      const apiKey = process.env.OPENAI_API_KEY;
      if (!apiKey) throw new Error("OPENAI_API_KEY is not configured.");
      const model = (process.env.OPENAI_SUMMARY_MODEL || process.env.OPENAI_MODEL || "gpt-4o-mini").trim();
      const response = await fetch("https://api.openai.com/v1/chat/completions", {
        method: "POST",
        headers: { "Content-Type": "application/json", Authorization: `Bearer ${apiKey}` },
        body: JSON.stringify({ model, messages, temperature: 0.2, max_tokens: 4000, stream: true }),
      });
      if (!response.ok) { 
        const text = await response.text().catch(() => "");
        const err = new Error(text || `OpenAI API responded with status ${response.status}`); 
        (err as any).status = response.status; 
        throw err; 
      }
      return new Response(createStreamHelper(response), { headers: { "Content-Type": "text/plain; charset=utf-8" } });
    };

    let streamResponse: Response;
    try {
      streamResponse = await callGroq();
    } catch (err) {
      const status = (err as any)?.status as number | undefined;
      const groqConfigured = Boolean((process.env.GROQ_API_KEY ?? "").trim());
      if (!groqConfigured) throw err;
      console.warn(`Groq failed (${status}), falling back to OpenAI`);
      streamResponse = await callOpenAI();
    }

    return streamResponse;
  } catch (error) {
    console.error("AI Summary generation failed:", error);
    return NextResponse.json({ error: error instanceof Error ? error.message : String(error) }, { status: 500 });
  }
}