import { NextResponse } from "next/server";

export async function POST(request: Request) {
  try {
    const { transcript, meetingContext } = (await request.json()) as { 
      transcript: string[]; 
      meetingContext?: { language?: string; region?: string; };
    };

    if (!transcript?.length) {
      return NextResponse.json({ error: "Transcript is empty or missing." }, { status: 400 });
    }

    const transcriptText = transcript.join("\n");
    const now = new Date();
    const dateStr = now.toLocaleDateString("en-US", { weekday: "long", year: "numeric", month: "long", day: "numeric" });
    const timeStr = now.toLocaleTimeString("en-US", { hour: "2-digit", minute: "2-digit", timeZoneName: "short" });

    // Build context-aware prompt
    const languageContext = meetingContext?.language === "nigerian-english" 
      ? `You are an expert at understanding Nigerian English, including local idioms, phrasing, and pronunciation patterns. Interpret Igbo, Yoruba, and Hausa words or phrases that appear in otherwise English conversations contextually.`
      : "";

    const systemPrompt = `You are a highly experienced corporate secretary with 20+ years writing formal board-level and executive meeting minutes for international companies.
${languageContext}

You are an expert at:
- Correcting obvious speech-to-text errors — repeated words, phonetic misspellings, filler words — without changing the speaker's meaning
- Attributing statements accurately to the correct named speaker
- Writing formal, professional meeting minutes that capture substance and intent, not just literal words

Your minutes must:
- Sound written by a human professional secretary, not an AI
- Use formal past tense ("The team discussed…", "It was agreed that…", "Mr Adeyemi proposed…")
- Capture the substance of discussions — the actual reasoning, positions, and debates
- Include all decisions with clear attribution
- Present action items in a structured table
- Be formatted in clean, professional Markdown`;

    const userPrompt = `Please produce complete, formal meeting minutes from the transcript below.

IMPORTANT INSTRUCTIONS:
- The transcript was generated by speech-to-text software and may contain errors — use your judgement to interpret meaning
- Speakers are identified by their name at the start of each line
- Do not omit any speaker or topic just because the transcription looks imperfect

MEETING DATE: ${dateStr}
MEETING TIME: ${timeStr}

TRANSCRIPT:
${transcriptText}

---

Write the minutes in this exact format:

# MEETING MINUTES

**Date:** ${dateStr}
**Time:** ${timeStr}
**Record Prepared By:** Quorum AI Secretary
**Status:** Official Record — Pending Approval

---

## 1. ATTENDANCE

*List every speaker identified in the transcript by name.*

---

## 2. CALL TO ORDER

*Who opened the meeting, time, stated purpose, and any quorum confirmation.*

---

## 3. PROCEEDINGS

*For each major topic discussed, write a full paragraph as a professional secretary would.*

### 3.1 [First Topic]

### 3.2 [Second Topic]

---

## 4. DECISIONS RECORDED

*Numbered list of every formal or informal decision made.*

1. 
2.

---

## 5. ACTION ITEMS

| # | Action Required | Owner | Target Date | Priority |
|---|-----------------|-------|-------------|----------|
| 1 | | | | High / Medium / Low |

---

## 6. MATTERS FOR FOLLOW-UP

*Items deferred, tabled, or requiring future discussion.*

---

## 7. ADJOURNMENT

*How and at what time the meeting concluded.*

---

*Prepared by Quorum AI Secretary · ${dateStr}*`;

    const messages = [
      { role: "system", content: systemPrompt },
      { role: "user", content: userPrompt },
    ] as const;

    const callGroq = async () => {
      const apiKey = process.env.GROQ_API_KEY;
      if (!apiKey) throw new Error("GROQ_API_KEY is not configured.");
      const response = await fetch("https://api.groq.com/openai/v1/chat/completions", {
        method: "POST",
        headers: { "Content-Type": "application/json", Authorization: `Bearer ${apiKey}` },
        body: JSON.stringify({
          model: process.env.GROQ_MODEL || "llama-3.3-70b-versatile",
          messages,
          temperature: 0.2,
          max_tokens: 4000,
        }),
      });
      const text = await response.text().catch(() => "");
      if (!response.ok) { 
        const err = new Error(text || `Groq API responded with status ${response.status}`); 
        (err as any).status = response.status; 
        throw err; 
      }
      const data = JSON.parse(text) as { choices?: Array<{ message?: { content?: string } }> };
      const minutes = data.choices?.[0]?.message?.content;
      if (!minutes) throw new Error("Groq returned an empty response.");
      return minutes;
    };

    const callOpenAI = async () => {
      const apiKey = process.env.OPENAI_API_KEY;
      if (!apiKey) throw new Error("OPENAI_API_KEY is not configured.");
      const model = (process.env.OPENAI_SUMMARY_MODEL || process.env.OPENAI_MODEL || "gpt-4o-mini").trim();
      const response = await fetch("https://api.openai.com/v1/chat/completions", {
        method: "POST",
        headers: { "Content-Type": "application/json", Authorization: `Bearer ${apiKey}` },
        body: JSON.stringify({ model, messages, temperature: 0.2, max_tokens: 4000 }),
      });
      const text = await response.text().catch(() => "");
      if (!response.ok) { 
        const err = new Error(text || `OpenAI API responded with status ${response.status}`); 
        (err as any).status = response.status; 
        throw err; 
      }
      const data = JSON.parse(text) as { choices?: Array<{ message?: { content?: string } }> };
      const minutes = data.choices?.[0]?.message?.content;
      if (!minutes) throw new Error("OpenAI returned an empty response.");
      return minutes;
    };

    let minutes: string;
    try {
      minutes = await callGroq();
    } catch (err) {
      const status = (err as any)?.status as number | undefined;
      const groqConfigured = Boolean((process.env.GROQ_API_KEY ?? "").trim());
      // Fall back to OpenAI for any Groq error, not just rate limits
      if (!groqConfigured) throw err;
      console.warn(`Groq failed (${status}), falling back to OpenAI`);
      minutes = await callOpenAI();
    }

    return NextResponse.json({ minutes });
  } catch (error) {
    console.error("AI Summary generation failed:", error);
    return NextResponse.json({ error: error instanceof Error ? error.message : String(error) }, { status: 500 });
  }
}